# Generated by Django 2.2.10 on 2020-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_productcategory_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_enable',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Категория Активна'),
        ),
    ]
