# Generated by Django 2.2.10 on 2020-05-10 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20200510_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_addr',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка ВК'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_lang',
            field=models.CharField(blank=True, max_length=32, verbose_name='язык ВК'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 17, 30, 56, 356158, tzinfo=utc)),
        ),
    ]
